image: node:4.4.4

pages:
  cache:
    paths:
    - node_modules/
    - bower_components/

  script:
    - npm install -g bower
    - npm install
    - bower install
    - grunt dist
  artifacts:
    paths:
    - public